---
AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 140
Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  Max: 80
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 10
